name: pet_app
description: A new Flutter project.

version: 1.0.0+1

environment:
     sdk: ">=2.12.0 <3.0.0"

dependencies:
     animated_splash_screen: ^1.3.0
     cached_network_image: ^3.1.0
     carousel_slider: ^4.0.0
     cupertino_icons: ^1.0.2
     file: ^6.1.4
     firebase_core: ^2.14.0
     firebase_storage: ^11.2.3
     flutter:
          sdk: flutter
     flutter_svg: ^0.22.0
     fluttertoast: ^8.1.1
     glassmorphism_ui: ^0.2.0
     google_fonts: ^2.1.1
     http: ^0.13.5
     image_picker: ^0.8.9
     lottie: ^1.4.3
     provider: ^6.0.3
     time_machine: ^0.9.17

dev_dependencies:
     flutter_test:
          sdk: flutter

flutter:
     uses-material-design: true

     assets:
          - assets/icons/
          - assets/images/
